name: servicios_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  generic_bloc_provider: ^1.0.9
  http: any
  shared_preferences: ^0.5.12+4
  firebase_auth: 
  google_sign_in: 
  image_picker: ^0.6.7+4
  multi_image_picker: ^4.7.11
  path_provider: ^1.6.14
  image: ^2.1.14
  google_maps_flutter: ^0.5.31
  google_maps_webservice: ^0.0.18
  permission: ^0.1.7
  provider: ^4.3.2+2
  file_picker: ^1.13.0+1
  intl: ^0.16.1
  url_launcher: ^5.7.4
  location: ^3.0.2
  location_permissions: ^3.0.0
  latlong: ^0.6.1
  geolocation: ^1.1.2
  screen: ^0.0.5
  smooth_star_rating: ^1.1.1
  gps: ^0.1.1
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.1
  firebase_core: ^0.5.0+1
  firebase_database: ^4.1.1
  geocoder: ^0.2.1
  geolocator: ^6.1.4+1
  locate: ^1.2.0
  webview_flutter: ^0.3.22
  culqi_flutter: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/fondo5.png
    - assets/images/fondo2.png
    - assets/images/fondo3.png
    - assets/images/arrow_back.png
    - assets/images/fondoP.png
    - assets/images/profesional.png
    - assets/images/solicitante.png
    - assets/images/fondoRegistrar.png
    - assets/images/profile.png
    - assets/images/email.png
    - assets/images/hardware.png
    - assets/images/casa.png
    - assets/images/student.png
    - assets/images/deporte.png
    - assets/images/mecanico.png
    - assets/images/fondoGaleria.png
    - assets/images/evento.png
    - assets/images/spa.png
    - assets/images/pets.png
    - assets/images/certificado.png
    - assets/images/certified.png
    - assets/images/chica.png
    - assets/images/escudo.png
    - assets/images/tarjeta.png
    - assets/images/pago.png
    - assets/images/add.png
    - assets/images/update.png
    - assets/images/verificado.png
    - assets/images/tarjetaPago.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
